# Generated by Django 3.1.1 on 2020-09-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0003_auto_20200918_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='examApp.user'),
            preserve_default=False,
        ),
    ]
